@baseUrl = http://localhost:3000

### Login
# @name loginAction
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "admin@user.com",
    "password": "admin"
}

###
POST {{baseUrl}}/refresh-token
Content-Type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4gVXNlciIsImVtYWlsIjoiYWRtaW5AdXNlci5jb20iLCJpYXQiOjE3NjIyNzc4MzEsImV4cCI6MTc2Mjg4MjYzMSwic3ViIjoiMSJ9.Ts42ZihYzsGC62l2yDk6LQt0cxY-AnduQNaZfnKbi0w"
}

###
GET {{baseUrl}}/protected
Authorization: Bearer {{ loginAction.response.body.access_token }}