@baseUrl = http://localhost:3000

### Login
# @name loginAction
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "admin@user.com",
    "password": "admin"
}

###
POST {{baseUrl}}/refresh-token
Content-Type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4gVXNlciIsImVtYWlsIjoiYWRtaW5AdXNlci5jb20iLCJpYXQiOjE3NjIyMjIzOTksImV4cCI6MTc2MjIyMjQ1OX0.304rVRtPlo932tikf6VjjKUFMu5kfaMfhf3MUZ-paJQ"
}